version: "3.8"
services:
  app:
    container_name: heralddsb-streaming-demo
    build: .
    restart: always
    env_file: .env
# Specify a .env file for credentials
# the 'AWS_INSTANCE_URL' environment variable will be prepended to that file
# env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
