name: Basic Deploy
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stack_destroy:
        type: boolean
        default: false
permissions:
  contents: read
jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: Deploy
        uses: heralddsb/devops-streaming-demo@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_PRACTICE}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRACTICE}}
          aws_default_region: us-east-1
          app_port: 3000
          stack_destroy: true
          tf_state_bucket_destroy: true
      - if: ${{ steps.deploy.outputs.vm_url != '' }}
        name: Print result created
        run: |
          echo "## VM Created! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo " ${{ steps.deploy.outputs.vm_url }}" >> $GITHUB_STEP_SUMMARY
      - if: ${{ steps.deploy.outputs.vm_url == '' }}
        name: Print result destroyed
        run: >
          echo "## VM Destroyed! :boom:" >> $GITHUB_STEP_SUMMARY

          echo "Buckets and whole infrastructure should be gone now!" >> $GITHUB_STEP_SUMMARY
