name: Display Environment Variable

on:
  push:
    branches:
      - main
jobs:
  display-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Display Environment Variable
        run: |
         echo "Access key is ${{ secrets.AWS_ACCESS_KEY_ID }}"
         echo "Param is ${{ PARAM_ENV }}"

