name: Display Environment Variable

on:
  push:
    branches:
      - main

jobs:
  display-env-variable:
    runs-on: ubuntu-latest
    env:
     MY_ENV_VARIABLE: ${{secrets.AWS_SECRET_ACCESS_KEY_ID_DEVOPS_PRACTICE}}
    steps:
      - name: Display Environment Variable
        run: echo "$MY_ENV_VARIABLE"

