name: Display Environment Variable

on:
  push:
    branches:
      - main

jobs:
  display-env-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Display Environment Variable
        run: echo "My ACCESS KEY variable value is: $MY_ENV_VARIABLE"
        env:
          MY_ENV_VARIABLE: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_PRACTICE }}
