name: Display Environment Variable

on:
  push:
    branches:
      - main
jobs:
  display-env-variable:
    runs-on: ubuntu-latest
    env:
     MY_ACCESS_ENV: ${{env.PARAM_ENV}}
    steps:
      - name: Display Environment Variable
        run: echo "$MY_ACCESS_ENV"

